table bedtime_screentime_project
	lineageTag: c342019c-1d09-419a-bee4-8252186bd900

	measure 'Average sleep' = AVERAGE(bedtime_screentime_project[total_sleep_hours])
		lineageTag: 4060c0a0-827c-43a1-bb8f-b3c4c70a8064

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average Screen Time' = AVERAGE(bedtime_screentime_project[bedtime_phone_minutes])
		lineageTag: 0f6f705f-4b85-4a77-83d6-c268315fd76e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total wakeup snoozes' = SUM((bedtime_screentime_project[morning_alarm_snoozes]))
		formatString: 0
		lineageTag: d443a222-6204-49a1-b997-1af5ae5680ae

	measure 'Average Fatigue Score' = AVERAGE(bedtime_screentime_project[next_day_fatigue_score])
		lineageTag: 37390d70-4fd9-4f86-bd95-308fa232fa9c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Deep Sleep %' = AVERAGE(bedtime_screentime_project[deep_sleep_pct])
		lineageTag: 66806a6a-821e-432c-9a47-faec03c00082

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg REM Sleep %' = AVERAGE(bedtime_screentime_project[rem_sleep_pct])
		lineageTag: 744d564f-4fb9-45ab-a77a-add4632dd40e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column user_id
		dataType: string
		lineageTag: f3380ad3-257b-49a5-a7e4-87a87d4d1c34
		summarizeBy: none
		sourceColumn: user_id

		annotation SummarizationSetBy = Automatic

	column age
		dataType: int64
		formatString: 0
		lineageTag: fc9bd9ff-82fc-4205-82e8-d017bedf8966
		summarizeBy: sum
		sourceColumn: age

		annotation SummarizationSetBy = Automatic

	column gender
		dataType: string
		lineageTag: ff70c77a-5926-4940-aa04-dbbfa39686ee
		summarizeBy: none
		sourceColumn: gender

		annotation SummarizationSetBy = Automatic

	column occupation_type
		dataType: string
		lineageTag: df76a9ec-9735-4730-9623-53b477d7aaca
		summarizeBy: none
		sourceColumn: occupation_type

		annotation SummarizationSetBy = Automatic

	column chronotype
		dataType: string
		lineageTag: 44dc766a-d1e0-4ca3-912b-cab8425dc92c
		summarizeBy: none
		sourceColumn: chronotype

		annotation SummarizationSetBy = Automatic

	column bedtime_phone_minutes
		dataType: int64
		formatString: 0
		lineageTag: 294d0cbd-6b6f-4409-98c9-4d9a63aedf1a
		summarizeBy: sum
		sourceColumn: bedtime_phone_minutes

		annotation SummarizationSetBy = Automatic

	column primary_bedtime_app
		dataType: string
		lineageTag: 1d5bc597-a695-415a-9241-d0b5ae5057df
		summarizeBy: none
		sourceColumn: primary_bedtime_app

		annotation SummarizationSetBy = Automatic

	column screen_brightness_pct
		dataType: int64
		formatString: 0
		lineageTag: 85f771f6-4eb4-4997-bc99-00cfc2c18fb6
		summarizeBy: sum
		sourceColumn: screen_brightness_pct

		annotation SummarizationSetBy = Automatic

	column blue_light_filter_active
		dataType: int64
		formatString: 0
		lineageTag: e1ad2d2a-7f8d-43b0-8cee-2fa92b54fcae
		summarizeBy: sum
		sourceColumn: blue_light_filter_active

		annotation SummarizationSetBy = Automatic

	column caffeine_post_5pm_mg
		dataType: int64
		formatString: 0
		lineageTag: 48a8040a-2478-4ef2-ad8e-e767844acf25
		summarizeBy: sum
		sourceColumn: caffeine_post_5pm_mg

		annotation SummarizationSetBy = Automatic

	column physical_activity_min
		dataType: int64
		formatString: 0
		lineageTag: 3749e803-f97d-4dd2-8f7f-09fdeea84fdd
		summarizeBy: sum
		sourceColumn: physical_activity_min

		annotation SummarizationSetBy = Automatic

	column sleep_latency_min
		dataType: double
		lineageTag: 03d48794-c31f-4da2-8cf7-218a38ca0ae8
		summarizeBy: sum
		sourceColumn: sleep_latency_min

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column total_sleep_hours
		dataType: double
		lineageTag: f6dacff8-8e4a-4f56-a6c4-42cb8a1c39b6
		summarizeBy: sum
		sourceColumn: total_sleep_hours

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column deep_sleep_pct
		dataType: double
		lineageTag: e9543b2c-e925-4572-8417-22a69f8774c8
		summarizeBy: sum
		sourceColumn: deep_sleep_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column rem_sleep_pct
		dataType: double
		lineageTag: abfd6161-b629-45a2-80a7-32b7869e68e7
		summarizeBy: sum
		sourceColumn: rem_sleep_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column morning_alarm_snoozes
		dataType: int64
		formatString: 0
		lineageTag: a309b2da-00af-457c-a0c5-9759387fc542
		summarizeBy: sum
		sourceColumn: morning_alarm_snoozes

		annotation SummarizationSetBy = Automatic

	column next_day_fatigue_score
		dataType: double
		lineageTag: 81fea077-0ca1-4766-9b84-3eb58ed498dd
		summarizeBy: sum
		sourceColumn: next_day_fatigue_score

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column sleep_debt_category
		dataType: string
		lineageTag: 6747c139-50ba-4fa5-80bd-f50a6777fddf
		summarizeBy: none
		sourceColumn: sleep_debt_category

		annotation SummarizationSetBy = Automatic

	partition bedtime_screentime_project = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\Power bi\6\bedtime_screentime_project.csv"),[Delimiter=",", Columns=18, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"user_id", type text}, {"age", Int64.Type}, {"gender", type text}, {"occupation_type", type text}, {"chronotype", type text}, {"bedtime_phone_minutes", Int64.Type}, {"primary_bedtime_app", type text}, {"screen_brightness_pct", Int64.Type}, {"blue_light_filter_active", Int64.Type}, {"caffeine_post_5pm_mg", Int64.Type}, {"physical_activity_min", Int64.Type}, {"sleep_latency_min", type number}, {"total_sleep_hours", type number}, {"deep_sleep_pct", type number}, {"rem_sleep_pct", type number}, {"morning_alarm_snoozes", Int64.Type}, {"next_day_fatigue_score", type number}, {"sleep_debt_category", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

